name: Build-Windows

on:
  pull_request:
    branches: [ master ]
    paths-ignore: 
    - '**/README.md'

env:
  BUILD_TYPE: MinSizeRel

jobs:
  Build-Windows:
    runs-on: windows-latest

    steps:   
    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Update submodules
      run: |
        git submodule update --remote

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build dependencies    
      run: |
        MSBuild.exe build\deps\SaffronEngine2D\ALL_BUILD.vcxproj /p:Configuration=MinSizeRel
    - name: Build project
      run: |
        MSBuild.exe build\ALL_BUILD.vcxproj /property:Configuration=MinSizeRel /property:OutDir="../example/windows/"
    - name: Commit
      run: |
        git checkout master
        git config --global user.name "Emil Karlsson"
        git config --global user.email "own.emka@gmail.com"
        git add example/windows/
        git commit -m "[🚚 Automatic] Generated Example Executable"
        git push
